FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive

# update ubuntu
RUN apt update
RUN apt-get update -qq

# install mysql and create the database
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y mysql-server 
RUN service mysql start && mysql -e "CREATE USER 'master'@'localhost' IDENTIFIED BY 'master';CREATE DATABASE db; GRANT ALL PRIVILEGES ON db.* TO 'master'@'localhost';"

# add the flask application and install requirements
RUN apt -y install python3-pip
RUN apt -y install vim
RUN mkdir /app
COPY . /app 
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# install firebase-admin
RUN pip install firebase-admin

# open ports, set environment variables, start the application
EXPOSE 8080 
ENV PORT 8080
ENV FLASK_ENV=development
CMD service mysql start && exec python3 app.py
# ----------------------------------------------------- 